version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    links:
      - frontend
    restart: always
    environment:
      DOMAINS: "domainName1.com -> http://frontend, domainName2.com -> http://frontend2"
      # STAGE: "production" # Don't use production until staging works
      FORCE_RENEW: "true"
    volumes:
      - https-portal-data:/var/lib/https-portal

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:3000"

  frontend2:
    container_name: frontend2
    build:
      context: .
      dockerfile: docker/frontend-2.Dockerfile
    ports:
      - "4000:4000"

volumes:
  https-portal-data:
